"""Generate wrapper launcher script with shim injection."""
import os
import subprocess
from pathlib import Path

from .config import Config
from .url_handler_shim import SHIM_TEMPLATE


class LauncherGenerator:
    """Generate launcher script that sets up environment for login fix."""

    def __init__(self, browser_path, debug=False):
        self.browser = browser_path
        self.debug = debug

    def create_launcher(self):
        """Create the launcher script and shims."""
        # Create directories
        Config.BIN_DIR.mkdir(parents=True, exist_ok=True)
        Config.SHIMS_DIR.mkdir(parents=True, exist_ok=True)

        # Create the xdg-open shim
        self._create_shim()

        # Create the main launcher
        self._create_launcher_script()

    def _create_shim(self):
        """Create xdg-open shim in shims directory."""
        shim_path = Config.SHIMS_DIR / "xdg-open"
        shim_path.write_text(SHIM_TEMPLATE)
        shim_path.chmod(0o755)

        # Also create kde-open5 shim if on KDE
        if self._is_kde():
            kde_shim = Config.SHIMS_DIR / "kde-open5"
            kde_shim.write_text(SHIM_TEMPLATE)
            kde_shim.chmod(0o755)

    def _is_kde(self):
        """Check if running KDE Plasma."""
        return os.environ.get("XDG_CURRENT_DESKTOP", "").upper() == "KDE"

    def _get_dbus_address(self):
        """Try to recover DBus session address."""
        # Check current environment
        dbus = os.environ.get("DBUS_SESSION_BUS_ADDRESS")
        if dbus:
            return dbus

        # Try pgrep to find from running processes
        try:
            result = subprocess.run(
                ["pgrep", "-u", str(os.getuid()), "-x", "dbus-daemon"],
                capture_output=True,
                text=True,
            )
            if result.returncode == 0:
                pid = result.stdout.strip().split("\n")[0]
                env_file = Path(f"/proc/{pid}/environ")
                if env_file.exists():
                    content = env_file.read_bytes()
                    for item in content.split(b"\x00"):
                        if item.startswith(b"DBUS_SESSION_BUS_ADDRESS="):
                            return item.decode()[25:]
        except Exception:
            pass

        return None

    def _get_qt_platform(self):
        """Determine Qt platform based on session."""
        session = os.environ.get("XDG_SESSION_TYPE", "x11")
        if session == "wayland":
            # Try wayland first, fallback to xcb
            return "wayland;xcb"
        return "xcb"

    def _create_launcher_script(self):
        """Create the main launcher bash script."""
        dbus_addr = self._get_dbus_address()
        qt_platform = self._get_qt_platform()

        script = f'''#!/usr/bin/env bash
# Packet Tracer launcher - generated by pt-installer
# This wrapper fixes the login button browser opening issue

export PT_HOME="{Config.PT_HOME}"
export PT_BROWSER="{self.browser}"

# Inject our shims directory first in PATH
export PATH="{Config.SHIMS_DIR}:$PATH"

# Qt WebEngine browser override - forces browser usage
export QT_QPA_WEBENGINE_BROWSER_EXECUTABLE="{self.browser}"

# Qt platform (wayland or x11)
export QT_QPA_PLATFORM="{qt_platform}"
export QT_AUTO_SCREEN_SCALE_FACTOR=1

# DBus session bus (critical for xdg-open/kde-open)
'''

        if dbus_addr:
            script += f'export DBUS_SESSION_BUS_ADDRESS="{dbus_addr}"\n'
        else:
            script += '''
# Attempt to recover DBus address
if [[ -z "$DBUS_SESSION_BUS_ADDRESS" ]]; then
    _dbus_pid=$(pgrep -u "$USER" -x dbus-daemon 2>/dev/null | head -1)
    if [[ -n "$_dbus_pid" ]]; then
        _dbus_addr=$(grep -z "^DBUS_SESSION_BUS_ADDRESS=" "/proc/$_dbus_pid/environ" 2>/dev/null | tr "\\0" "\\n" | sed "s/^DBUS_SESSION_BUS_ADDRESS=//" | head -1)
        [[ -n "$_dbus_addr" ]] && export DBUS_SESSION_BUS_ADDRESS="$_dbus_addr"
    fi
fi
'''

        script += '''
# WebEngine stability
export WEBKIT_DISABLE_COMPOSITING_MODE=1
export QTWEBENGINE_DISABLE_SANDBOX=1

# Debug mode
'''

        if self.debug:
            script += 'echo "[PT-Launcher] Starting with:"\n'
            script += 'echo "  PT_BROWSER=$PT_BROWSER"\n'
            script += 'echo "  DBUS_SESSION_BUS_ADDRESS=$DBUS_SESSION_BUS_ADDRESS"\n'
            script += 'echo "  QT_QPA_PLATFORM=$QT_QPA_PLATFORM"\n'
            script += 'echo "  PATH=$PATH"\n'

        script += f'''
# Launch AppImage
exec "{Config.APPIMAGE_PATH}" "$@"
'''

        Config.LAUNCHER_PATH.write_text(script)
        Config.LAUNCHER_PATH.chmod(0o755)
